// <auto-generated />
namespace seanca13.IdentityMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class validim : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(validim));
        
        string IMigrationMetadata.Id
        {
            get { return "202009032159284_validim"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
